### ISSUE TITLE
Electron firmware update fails

### ISSUE THREAD

**Issue by fguptill** [spark/device-updater#28]
My electron has installed firmware version 0.5.1
I downloaded, installed, and ran "particle_firmware_manager-v0.5.3-windows.exe" on my Windows 10 laptop.  It invited me to connect a Particle device.
I connected my Electron via USB directly to the laptop.
The firmware manager immediately identified my Electron and invited me to "update to 0.5.3".  I clicked on the big blue bar.  It responded "Updating to 0.5.3", but nothing else happened.  I waited for 4 minutes while the Electron flashed blue (listening mode).  Still nothing happened, so I closed the firmware manager, 
Next I disconnected the Electron from USB cable, placed it in Safe Mode, re-launched the firmware manager, reconnected the USB cable, and clicked on the big blue bar.  This time the progress bar turned magenta as it scooted half way across the screen and then stalled.  I watched the little round progress indicator circle around for 2 minutes as the Electron LED flashed blue (listening mode).

Next, I closed the "Particle Device Updater" window and placed the device in DFU mode. I launched Particle CLI and executed "particle update".  The response I got was:
"> Your device is ready for a system update.
> This process should take about 30 seconds. Here goes!

! System firmware update successfully completed!

> Your device should now restart automatically.
> You may need to re-flash your application to the device."

Unfortunately my device still has firmware version 0.5.1

Do I need to update the firmware?  What happens if I do not update it?  How do I update it?

Phred

**Comment by m-mcgowan** [comment]
Sorry to hear of these problems. Please try flashing tinker to your device, especially if your application is using Serial to output anything.

**Comment by fguptill** [comment]
I have no problem loading and running apps.  I am doing active development involving constantly revising and testing apps.  I don't see what is the point in flashing tinker - just another application?
My question concerns only whether I should update the firmware from version 0.5.1, and if so, how to do it.

**Comment by m-mcgowan** [comment]
You shouldn't need to update system firmware - that's of course the point of the firmware manager to take care of that, but your app may be interfering with the update process. Your description indicates this, since it got further in safe mode, when your app is not running, hence that's why flashing tinker will help since it is a known quantity. 

If you want to try an alternate route, you can install our CLI and use `particle update` to update firmware, but it's a more involved process.

**Comment by fguptill** [comment]
So, just to make sure that I understand you, are you saying that which app is loaded into the Electron's memory at the time of the update can affect the success or failure of the firmware update?

Also, when you suggest using particle update via the Particle CLI, are you suggesting something different from what I reported trying in my original post?  That reported a successful completion, but did not update my firmwRe to anything more recent than 0.5.1

Is it possible that my Electron is so old that it cannot run firmware newer than version 0.5.1?

**Comment by fguptill** [comment]
Updating Particle CLI resolved the issue.
